sudo:required
services:
  - docker

before_install:
  - docker build -t federicotorres233/react-test -f ./web/Dockerfile.dev ./web

script:
  - docker run federicotorres233/react-test npm test -- --coverage

after_success:
  - docker build -t federicotorres233/multi-client ./web
  - docker build -t federicotorres233/multi-nginx ./nginx
  - docker build -t federicotorres233/multi-server ./server
  - docker build -t federicotorres233/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push federicotorres233/multi-client
  - docker push federicotorres233/multi-nginx
  - docker push federicotorres233/multi-server
  - docker push federicotorres233/multi-worker

deploy:
  provider: elasticbeanstalk
  region: $REGION
  app: multi-docker
  env: Multidocker-env
  bucket_name: $BUCKET_NAME
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
